site_name: PON dot WIKI
site_url: https://pon.wiki
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - announce.dismiss
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
nav:
  - GPON:
    - gpon/index.md
  - XGS-PON:
    - xgs-pon/index.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/8311-886329492438671420
repo_url: https://github.com/up-n-atom/8311
