site_name: pon.wiki
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - announce.dismiss
  custom_dir: overrides
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/8311-886329492438671420
repo_url: https://github.com/up-n-atom/8311
