site_name: PON dot WIKI
site_url: https://pon.wiki
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - announce.dismiss
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
plugins:
  - blog:
      blog_dir: guides
  - search
nav:
  - Guides:
    - guides/index.md
  - GPON:
    - gpon/index.md
  - XGS-PON:
    - xgs-pon/index.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/8311-886329492438671420
copyright: Copyright &copy; 2024
repo_url: https://github.com/up-n-atom/8311
repo_name: up-n-atom/8311
